package Kalkulator;


/**
* Kalkulator/KalkulatorInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kalkulator.idl
* œroda, 3 marca 2021 12:11:09 CET
*/

public interface KalkulatorInterface extends KalkulatorInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface KalkulatorInterface
