package Kalkulator;


/**
* Kalkulator/KalkulatorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kalkulator.idl
* œroda, 3 marca 2021 12:11:09 CET
*/

public interface KalkulatorInterfaceOperations 
{
  String add (double x, double y);
  String subtract (double a, double b);
  String multiply (double x, double y);
  String divide (double a, double b);
  String addComplexNumbers (double xRe, double yRe, double xIm, double yIm);
  String subtractComplexNumbers (double xRe, double yRe, double xIm, double yIm);
  String multiplyComplexNumbers (double xRe, double yRe, double xIm, double yIm);
  String divideComplexNumbers (double xRe, double yRe, double xIm, double yIm);
  String random ();
  void shutdown ();
} // interface KalkulatorInterfaceOperations
