package Kalkulator;

/**
* Kalkulator/KalkulatorInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kalkulator.idl
* œroda, 3 marca 2021 12:11:09 CET
*/

public final class KalkulatorInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Kalkulator.KalkulatorInterface value = null;

  public KalkulatorInterfaceHolder ()
  {
  }

  public KalkulatorInterfaceHolder (Kalkulator.KalkulatorInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Kalkulator.KalkulatorInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Kalkulator.KalkulatorInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Kalkulator.KalkulatorInterfaceHelper.type ();
  }

}
